# Use this only if SIM is enabled
#metricPrefix: "Custom Metrics|Linux Monitor|"

# If SIM is not enabled, then use this
metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Linux Monitor|"
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java

# NFS mounts for which mount data and its I/O data will be reported.
# displayName: the name with which the metric is reported in AppD Metric Browser. If empty, metric is reported with fileSystem as its name.
mountedNFS:
      - fileSystem: "devfs"
        displayName: "NFS1"

# Filters to fetch data only for the configured.
# Ex: ["*"] fetches all disks
# ["sda.*", "ram1", "loop0"]
filters:
  diskIncludes: [".*"]
  cpuIncludes: [".*"]

# Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters

metricCharacterReplacer:
  - replace: "%"
    replaceWith: ""


# number of concurrent tasks
numberOfThreads: 5

#derivedMetrics:
#    - derivedMetricPath: "diskStats|I/O ops per sec"
#      formula: "(diskStats|reads completed successfully + diskStats|writes completed)/60"
#      collectDelta: "true"
#      metricType: "OBS.AVG.COL"

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
# Values provided here can be overridden if the same field is configured in either controller-info.xml or system properties.
controllerInfo:
  controllerHost: ""  # -Dappdynamics.controller.hostName
  controllerPort:  # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "admin" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "j+0oxTzUtw2xAdaq4UUq/Q==" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName


#Encryption key for your controllerInfo password
encryptionKey: "abcd"

#Files used by the extension to fetch monitoring data
# /proc/stat
# /proc/net/dev
# /proc/diskstats
# /proc/meminfo
# /proc/sys/fs/file-nr
# /proc/sys/fs/inode-nr
# /proc/sys/fs/dentry-state
# /proc/loadavg
# /proc/vmstat
# proc/net/sockstat
